/** API-key credential provisioning and learner-session administration. */
import { requireApiKey, hashPassword, verifyPassword } from "../auth.mjs";
import { audit } from "../db/audit.mjs";
import { upsertPerson, passwordFor, setPassword, subjectsWithLogin,
  personBySubjectId, credentialByIdentifier, personById, markCredentialUsed } from "../db/waypoint.mjs";
import { mintLearnerSession, verifyLearnerSession, endLearnerSession,
  endAllLearnerSessions } from "../learner-session.mjs";

const key = (req,res,ctx) => { const a=requireApiKey(req); return a.error ? ctx.json(res,a.status,{error:a.error}) : null; };
export const routes = {
  "POST /api/auth/login": async (req,res,ctx) => { const b=await ctx.readJson(req),who=String(b.identifier||"").toLowerCase(); if(ctx.loginLocked(who))return ctx.json(res,429,{error:"Too many attempts. Try again in a few minutes."}); const c=who&&credentialByIdentifier(String(b.identifier)),good=c&&verifyPassword(String(b.password||""),c.secret_hash); if(!good){ctx.recordLoginFailure(who);return ctx.json(res,401,{error:"Incorrect email or password"});} ctx.clearLoginFailures(who); markCredentialUsed(c.id); const p=personById(c.person_id),token=mintLearnerSession(p.id,{ip:req.socket.remoteAddress,user_agent:req.headers["user-agent"]}); audit({actor:`subject:${p.subject_id}`,action:"signin",entity:"person",entity_id:p.subject_id,ip:req.socket.remoteAddress}); return ctx.json(res,200,{token,must_change_password:!!c.must_change,person:{subject_id:p.subject_id,name:p.name,email:p.email}}); },
  "POST /api/auth/logout": async (req,res,ctx) => { const h=req.headers["authorization"]||"",token=h.startsWith("Bearer ")?h.slice(7):null; if(token){const id=verifyLearnerSession(token);endLearnerSession(token);if(id){const p=personById(id);audit({actor:`subject:${p?.subject_id??id}`,action:"signout",entity:"person",entity_id:p?.subject_id??String(id),ip:req.socket.remoteAddress});}} return ctx.json(res,200,{ok:true}); },
  "GET /api/logins": async (req,res,ctx) => { if(key(req,res,ctx))return; const sid=ctx.url.searchParams.get("subject_id"); if(!sid)return ctx.json(res,200,{subject_ids:subjectsWithLogin()}); const p=personBySubjectId(sid),c=p&&passwordFor(p.id); return ctx.json(res,200,{has_login:!!c,login:c?c.identifier:null,last_used_at:c?c.last_used_at:null}); },
  "POST /api/users": async (req,res,ctx) => { if(key(req,res,ctx))return; const b=await ctx.readJson(req); if(!b.subject_id)return ctx.json(res,400,{error:"subject_id required"}); const person=upsertPerson(b); let credential=passwordFor(person.id),issued=false; if(b.password&&(!credential||b.reset_password)){const identifier=b.identifier||b.email;if(!identifier)return ctx.json(res,400,{error:"identifier or email required to set a password"}); credential=setPassword({person_id:person.id,identifier,secret_hash:hashPassword(String(b.password)),must_change:b.must_change?1:0});issued=true;} return ctx.json(res,200,{person,issued,credential:credential&&{identifier:credential.identifier,must_change:!!credential.must_change}}); },
  "POST /api/people/end-sessions": async (req,res,ctx) => { if(key(req,res,ctx))return; const b=await ctx.readJson(req),p=b.subject_id&&personBySubjectId(String(b.subject_id)); if(!p)return ctx.json(res,404,{error:"unknown subject"}); endAllLearnerSessions(p.id); return ctx.json(res,200,{ok:true,subject_id:p.subject_id}); }
};
