/**
 * The front door.
 *
 * The application is restricted to known IP addresses. That is the right
 * default for a demo box holding supervision records, and it is useless if
 * getting back in means SSHing from a hotel lobby. So one hostname stays open:
 * prove you know the passphrase, and your current address is added.
 *
 * Three decisions worth explaining.
 *
 * **It reads your address rather than asking for it.** A field to type an IP
 * into is a field to type the wrong IP into, and the one address that is
 * certainly right is the one the request arrived from.
 *
 * **Grants expire.** An allowlist nobody prunes becomes a list of every café
 * anyone ever worked from. Each entry carries a timestamp and is swept.
 *
 * **The restriction lives in Caddy, not the firewall.** A firewall filters by
 * port, so blocking 443 would mean this page had to be served over plain HTTP
 * — and the passphrase with it. Caddy filters by hostname, so this page gets
 * TLS like everything else.
 *
 * Zero dependencies, like the rest of this project.
 */

import { createServer } from "node:http";
import { scryptSync, timingSafeEqual, randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { pathToFileURL } from "node:url";

const run = promisify(execFile);

const PORT       = +(process.env.DOOR_PORT || 8099);
const HASH       = process.env.DOOR_HASH || "";
const GRANTS     = process.env.DOOR_GRANTS || "/var/lib/doorman/grants.json";
const SNIPPET    = process.env.DOOR_SNIPPET || "/etc/caddy/allowed.caddy";
const GRANT_DAYS = +(process.env.DOOR_GRANT_DAYS || 7);
const APP_URL    = process.env.DOOR_APP_URL || "/";

/* Addresses that are always allowed, whatever the grants file says — so a
   mistake in here cannot lock everybody out of everything at once. */
const PERMANENT = (process.env.DOOR_PERMANENT || "").split(/[,\s]+/).filter(Boolean);

/* ---------------------------------------------------------------- *
 * the passphrase                                                     *
 * ---------------------------------------------------------------- */

/** scrypt, salt embedded. Same format the application uses for passwords. */
export const hashPassphrase = plain => {
  const salt = randomBytes(16).toString("hex");
  return `scrypt$${salt}$${scryptSync(plain, salt, 64).toString("hex")}`;
};

function verify(plain, stored) {
  const [scheme, salt, hash] = String(stored).split("$");
  if (scheme !== "scrypt" || !salt || !hash) return false;
  const a = Buffer.from(scryptSync(String(plain), salt, 64).toString("hex"));
  const b = Buffer.from(hash);
  return a.length === b.length && timingSafeEqual(a, b);
}

/* ---------------------------------------------------------------- *
 * grants                                                             *
 * ---------------------------------------------------------------- */

const load = () => {
  try { return JSON.parse(readFileSync(GRANTS, "utf8")); } catch { return []; }
};

/**
 * Write the grants file AND the Caddy snippet, then reload Caddy.
 *
 * The snippet is generated, never edited by hand: two lists of who may enter
 * would disagree within a week, and the one that disagreed silently would be
 * the one actually enforcing.
 */
async function persist(grants) {
  const live = grants.filter(g => new Date(g.until) > new Date());
  writeFileSync(GRANTS, JSON.stringify(live, null, 2));

  const ips = [...new Set([...PERMANENT, ...live.map(g => g.ip)])];
  writeFileSync(SNIPPET,
    `# Generated by doorman. Do not edit — it is rewritten on every grant.\n`
  + `@denied not remote_ip ${ips.join(" ")}\n`
  + `respond @denied "Not from this address. Visit the front door to add it." 403\n`);

  await run("systemctl", ["reload", "caddy"]);
  return live;
}

/* ---------------------------------------------------------------- *
 * resetting the demo                                                 *
 * ---------------------------------------------------------------- */

/**
 * Why the demo reset lives HERE and not in the officer console.
 *
 * Two reasons, and the second is the one that decided it.
 *
 * **It is scaffolding, and the console is the product.** A "clear the demo"
 * button inside the thing being sold is visible to whoever is looking over the
 * operator's shoulder. Here, only the person holding the passphrase ever sees
 * it — which is the person running the demo.
 *
 * **This process can actually do it.** A full reset means stopping the app,
 * swapping the database file, and starting it again. The app cannot do that to
 * itself: it is the process holding the file open, and it cannot stop itself
 * mid-request and come back to finish answering. The doorman is a separate
 * service, so it can. The console version could only ever have deleted rows.
 */
const RESET_CMD = process.env.DOOR_RESET_CMD || "/usr/local/bin/waypoint-demo";
const RESET_ENABLED = process.env.DOOR_RESET !== "0";

/**
 * A ticket to reset, minted only by getting the passphrase right.
 *
 * Not a hidden field carrying the passphrase back: that would put it in the
 * DOM, in browser history and in any screenshot of the page. Same rule as
 * everywhere else here — a short-lived, single-use, server-minted token, bound
 * to the address that earned it.
 *
 * Ten minutes, because this is used within seconds of signing in. A tab left
 * open on a desk overnight is not a way to wipe a demo.
 */
const resetTokens = new Map();
const RESET_TTL_MS = 10 * 60 * 1000;

function mintResetToken(ip) {
  const token = randomBytes(24).toString("base64url");
  resetTokens.set(token, { ip, until: Date.now() + RESET_TTL_MS });
  return token;
}

/** Single use: taken from the map whether or not the reset then succeeds. */
function takeResetToken(token, ip) {
  const t = resetTokens.get(token);
  if (!t) return false;
  resetTokens.delete(token);
  return t.ip === ip && t.until > Date.now();
}

/* Failures per address. In memory on purpose: a restart forgiving a few
   attempts is a smaller problem than a file somebody has to clear by hand. */
const failures = new Map();
const LOCK_AFTER = 5;
const LOCK_MS = 15 * 60 * 1000;

function locked(ip) {
  const f = failures.get(ip);
  if (!f) return false;
  if (Date.now() - f.at > LOCK_MS) { failures.delete(ip); return false; }
  return f.n >= LOCK_AFTER;
}

/* ---------------------------------------------------------------- *
 * the page                                                           *
 * ---------------------------------------------------------------- */

/**
 * @param allowed    this address already gets through. The permanent entries
 *                   never see the door otherwise, which is exactly the person
 *                   who needs the reset button — so the page has to work for
 *                   somebody who is not locked out and never mislead them
 *                   about why they are here.
 * @param resetToken present once the passphrase has been proved. Its presence
 *                   IS the authorisation to show the reset control.
 */
const page = (ip, message = "", kind = "", { allowed = false, resetToken = null } = {}) => `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Waypoint — access</title>
<style>
  :root { color-scheme: light dark;
    --ink:#0f172a; --muted:#64748b; --line:#e2e8f0; --bg:#f1f5f9;
    --surface:#fff; --brand:#2563eb; --ok:#059669; --err:#dc2626 }
  @media (prefers-color-scheme: dark) { :root {
    --ink:#e8edf5; --muted:#94a3b8; --line:#1e293b; --bg:#0b1220; --surface:#111a2b } }
  * { box-sizing:border-box }
  body { margin:0; min-height:100vh; display:grid; place-items:center;
    background:var(--bg); color:var(--ink); padding:24px;
    font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif }
  .card { width:100%; max-width:400px; background:var(--surface);
    border:1px solid var(--line); border-radius:16px; padding:30px }
  h1 { margin:0 0 6px; font-size:19px; letter-spacing:-.3px }
  p  { margin:0 0 20px; color:var(--muted); font-size:14px }
  .ip { font-variant-numeric:tabular-nums; font-weight:700; color:var(--ink) }
  label { display:block; font-size:13px; font-weight:650; margin-bottom:7px }
  input { width:100%; padding:12px 13px; font:inherit; border-radius:10px;
    border:1px solid var(--line); background:var(--bg); color:var(--ink) }
  input:focus { outline:none; border-color:var(--brand);
    box-shadow:0 0 0 3px color-mix(in srgb, var(--brand) 18%, transparent) }
  button { width:100%; margin-top:14px; padding:12px; font:inherit; font-weight:700;
    border:0; border-radius:10px; background:var(--brand); color:#fff; cursor:pointer }
  button:hover { filter:brightness(1.08) }
  .msg { margin:0 0 18px; padding:11px 13px; border-radius:10px; font-size:13.5px }
  .msg.ok  { background:color-mix(in srgb, var(--ok) 12%, transparent); color:var(--ok) }
  .msg.err { background:color-mix(in srgb, var(--err) 12%, transparent); color:var(--err) }
  .foot { margin:18px 0 0; font-size:12.5px; color:var(--muted) }
  .sep { margin:24px 0 0; padding-top:20px; border-top:1px solid var(--line) }
  .sep h2 { margin:0 0 6px; font-size:14.5px; letter-spacing:-.2px }
  .sep p { margin:0 0 14px; font-size:13px }
  button.quiet { background:transparent; color:var(--err);
    border:1px solid color-mix(in srgb, var(--err) 35%, transparent) }
  button.quiet:hover { filter:none;
    background:color-mix(in srgb, var(--err) 8%, transparent) }
</style></head><body>
<div class="card">
  <h1>Waypoint</h1>
  <p>You are connecting from <span class="ip">${ip}</span>.
     ${allowed ? "This address already gets through."
               : "This address is not yet allowed through."}</p>
  ${message ? `<p class="msg ${kind}">${message}</p>` : ""}
  <form method="POST">
    <label for="p">Passphrase</label>
    <input id="p" name="passphrase" type="password" autocomplete="current-password"
           autofocus required>
    <button type="submit">${allowed ? "Confirm passphrase" : "Let me in"}</button>
  </form>
  ${resetToken && RESET_ENABLED ? `
  <div class="sep">
    <h2>Do you want a clean demo database?</h2>
    <p>Puts everything back to the saved baseline: the recordings, transcripts,
       summaries and action items from previous demos are cleared, so this one
       generates them live. Subjects, visits, cases and courses are untouched.
       The current state is snapshotted first.</p>
    <form method="POST" action="/reset">
      <input type="hidden" name="token" value="${resetToken}">
      <button class="quiet" type="submit">Reset the demo</button>
    </form>
  </div>` : ""}
  <p class="foot">Access lasts ${GRANT_DAYS} days, then this address drops off
     again. Demo system — seeded data only.</p>
</div></body></html>`;

/* ---------------------------------------------------------------- *
 * the server                                                         *
 * ---------------------------------------------------------------- */

const clientIp = req =>
  (req.headers["x-forwarded-for"] || "").split(",")[0].trim()
  || req.socket.remoteAddress?.replace(/^::ffff:/, "")
  || "unknown";

const html = (res, code, body) => {
  res.writeHead(code, { "Content-Type": "text/html; charset=utf-8",
                        "Cache-Control": "no-store",
                        "X-Content-Type-Options": "nosniff",
                        "Referrer-Policy": "no-referrer" });
  res.end(body);
};

/**
 * Only listen when this file IS the program.
 *
 * set-passphrase.mjs imports hashPassphrase from here, and a module that binds
 * a port the moment it is imported cannot be borrowed from — the helper died
 * with EADDRINUSE against the very service it was meant to configure. A file
 * that does something on import can only ever be run, never reused.
 */
const isMain = import.meta.url === pathToFileURL(process.argv[1] || "").href;

/** Is this address through already — permanently, or by an unexpired grant? */
const isAllowed = ip =>
  PERMANENT.includes(ip)
  || load().some(g => g.ip === ip && new Date(g.until) > new Date());

/**
 * Run the reset, on the operator's behalf.
 *
 * `--yes` because there is no terminal here to type into. The confirming
 * already happened, in a browser, against a passphrase — asking twice in two
 * different places is how people learn to click through prompts.
 */
function runReset() {
  return run(RESET_CMD, ["reset", "--yes"], { timeout: 120000 })
    .then(({ stdout, stderr }) => ({ ok: true, output: `${stdout}${stderr}` }))
    .catch(e => ({ ok: false,
                   output: `${e.stdout || ""}${e.stderr || ""}` || e.message }));
}

export function start() {
createServer(async (req, res) => {
  const ip = clientIp(req);
  const url = new URL(req.url || "/", "http://localhost");

  if (req.method === "GET")
    return html(res, 200, page(ip, "", "", { allowed: isAllowed(ip) }));
  if (req.method !== "POST") { res.writeHead(405); return res.end(); }

  if (locked(ip)) {
    console.log(`[doorman] locked out ${ip}`);
    return html(res, 429, page(ip,
      "Too many attempts. Wait fifteen minutes.", "err",
      { allowed: isAllowed(ip) }));
  }

  let body = "";
  for await (const chunk of req) {
    body += chunk;
    if (body.length > 4096) { res.writeHead(413); return res.end(); }
  }
  const form = new URLSearchParams(body);

  /* ---- the reset, authorised by a token the passphrase minted ---- */
  if (url.pathname === "/reset") {
    if (!RESET_ENABLED) { res.writeHead(404); return res.end(); }

    if (!takeResetToken(form.get("token") || "", ip)) {
      console.log(`[doorman] refused a reset from ${ip} — token bad or expired`);
      return html(res, 403, page(ip,
        "That reset link has expired. Enter the passphrase again.", "err",
        { allowed: isAllowed(ip) }));
    }

    console.log(`[doorman] demo reset requested by ${ip}`);
    const r = await runReset();
    console.log(`[doorman] reset ${r.ok ? "completed" : "FAILED"}`);
    if (!r.ok) console.error(r.output);

    /* No new token afterwards: one press, one reset. Wanting a second means
       going through the passphrase again, which takes seconds and makes an
       accidental double-reset something you have to mean. */
    return html(res, r.ok ? 200 : 500, page(ip,
      r.ok ? "The demo is back to its baseline. Recordings, transcripts, "
           + "summaries and action items are cleared."
           : "The reset did not run. Nothing was changed — check "
           + "<code>journalctl -u doorman</code>.",
      r.ok ? "ok" : "err",
      { allowed: isAllowed(ip) }));
  }

  const given = form.get("passphrase") || "";

  if (!HASH || !verify(given, HASH)) {
    const f = failures.get(ip) || { n: 0 };
    failures.set(ip, { n: f.n + 1, at: Date.now() });
    console.log(`[doorman] refused ${ip} (attempt ${f.n + 1})`);
    /* One message whether the passphrase was wrong or none is configured —
       "no passphrase is set" tells somebody exactly what to try next. */
    return html(res, 401, page(ip, "That is not the passphrase.", "err",
      { allowed: isAllowed(ip) }));
  }

  failures.delete(ip);

  /* A permanently-allowed address has nothing to grant itself.
   *
   * That is the operator, who never sees this page in the ordinary course of
   * things — and is exactly the person who wants the reset. Rewriting Caddy to
   * add somebody who is already in the PERMANENT list would be a no-op with a
   * service reload attached, and the honest answer to "you are already through"
   * is to say so rather than to perform letting them in. */
  const already = PERMANENT.includes(ip);
  const token = RESET_ENABLED ? mintResetToken(ip) : null;

  if (already) {
    console.log(`[doorman] passphrase confirmed by ${ip} (permanently allowed)`);
    return html(res, 200, page(ip,
      `This address is permanently allowed — nothing to change. `
    + `<a href="${APP_URL}">Open Waypoint</a>.`, "ok",
      { allowed: true, resetToken: token }));
  }

  const grants = load().filter(g => g.ip !== ip);
  const until = new Date(Date.now() + GRANT_DAYS * 864e5).toISOString();
  grants.push({ ip, until, granted_at: new Date().toISOString(),
                user_agent: String(req.headers["user-agent"] || "").slice(0, 120) });

  try {
    await persist(grants);
    console.log(`[doorman] allowed ${ip} until ${until}`);
  } catch (e) {
    console.error(`[doorman] could not apply the grant:`, e.message);
    return html(res, 500, page(ip,
      "The passphrase was right, but the change could not be applied. "
    + "Tell whoever runs this.", "err", { allowed: false }));
  }

  return html(res, 200, page(ip,
    `Done — this address is allowed for ${GRANT_DAYS} days. `
  + `<a href="${APP_URL}">Open Waypoint</a>.`, "ok",
    { allowed: true, resetToken: token }));
}).listen(PORT, "127.0.0.1", () => {
  console.log(`[doorman] listening on 127.0.0.1:${PORT}`);
  if (!HASH) console.error("[doorman] DOOR_HASH is not set — nobody can get in");
  /* Expired grants are swept hourly rather than only when somebody knocks,
     so an address does not stay allowed indefinitely just because nothing
     happened to trigger a rewrite. */
  setInterval(() => {
    const before = load().length;
    persist(load()).then(live => {
      if (live.length !== before)
        console.log(`[doorman] swept ${before - live.length} expired grant(s)`);
    }).catch(e => console.error("[doorman] sweep failed:", e.message));
  }, 60 * 60 * 1000).unref();
});
}

if (isMain) start();
